
import mysql.connector.errors as Error


class Equipements_activites:

	def __init__(self,database):
		self.database=database

	def createTableEquipements_Assoc_activites(self):
		'''
			Cree la table equipements_Assoc_activites, la table association entre les tables equipement et activite
				numeroActivite - type integer, l'identifiant et la clef primaire de la table activite
				numeroEquipement - type integer, l'identifiant de l'equipement utilis√© par une activite
		'''
		try:
			self.database.execute("CREATE TABLE equipements_Assoc_activites(numeroActivite integer , numeroEquipement integer)")
		except Error.ProgrammingError:
			print ("TABLE equipements_Assoc_activites : creation impossible car la table existe deja")


	def insertInTableEquipements_Assoc_activites(self,numeroActivite,numeroEquipement):
		try:
			self.database.execute("INSERT INTO equipements_Assoc_activites (numeroActivite, numeroEquipement) VALUES (%s,%s)",(numeroActivite,numeroEquipement))
		except Exception:
			print("Vous ne pouvez pas rentrer deux numeroActivite identique")


	def deleInTableEquipements_Assoc_activites(self,numeroActivite):
		try:
			self.database.execute("DELETE FROM equipements_Assoc_activites WHERE equipements_activites.numeroActivite=(%s)",(numeroActivite,))
		except Exception:
			print("Ce numeroActivite n'existe pas")

	
	# AJOUT DES CLEFS ETRANGERES

	def addForeignKeyEquipement(self):
		try:
			self.database.execute("ALTER TABLE equipements_Assoc_activites ADD CONSTRAINT numeroEquipement FOREIGN KEY (numeroEquipement) REFERENCES equipement(idEquipement)")
		except Exception :
			print("this key is already exist")


	def addCle_Etrangere_Activite(self):
		try:
			self.database.execute("ALTER TABLE equipements_Assoc_activites ADD CONSTRAINT numeroActivite FOREIGN KEY (numeroActivite) REFERENCES activite(numeroActivite)")
		except Exception :
			print("this key is already exist")


	def dropCle_Etrangere_Equipement(self):
		try:
			self.database.execute("ALTER TABLE equipements_Assoc_activites DROP FOREIGN KEY numeroEquipement ")
		except Error.DatabaseError:
			print("TABLE activite : clef etrangere inexistante")


	def dropCle_Etrangere_Activite(self):
		try:
			self.database.execute("ALTER TABLE equipements_Assoc_activites DROP FOREIGN KEY numeroActivite ")
		except Error.DatabaseError:
			print("TABLE activite : clef etrangere inexistante")	


	def dropTableEquipements_Assoc_activites(self):
		try:
			self.database.execute("DROP TABLE IF EXISTS equipements_Assoc_activites")
		except Exception:
			print ("Table inexistante")		
	
